{% set name = "MDAnalysisData" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: 1958636ab982e86bde5358e3cad29a484aa64fafbb320a8d4064b6538aa38fc1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - setuptools
    - tqdm

test:
  requires:
    - python {{ python_min }}
  imports:
    - MDAnalysisData

about:
  home: https://github.com/MDAnalysis/MDAnalysisData
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Example MD Simulation Data
  description: |
    The MDAnalysisData package unifies access to test and example
    trajectories that can be used for workshops and extended tests.
  doc_url: https://www.mdanalysis.org/MDAnalysisData/
  dev_url: https://github.com/MDAnalysis/MDAnalysisData

extra:
  recipe-maintainers:
    - IAlibay
    - orbeckst
