{% set name = "MDAnalysisData" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e0cbec31c79075148f007e6e6914eec7ef4a9307283a6d81e2896240d92f97d8

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six
    - setuptools
    - tqdm

test:
  imports:
    - MDAnalysisData

about:
  home: https://github.com/MDAnalysis/MDAnalysisData
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Example MD Simulation Data'
  description: |
    The MDAnalysisData package unifies access to test and example
    trajectories that can be used for workshops and extended tests.
  doc_url: https://www.mdanalysis.org/MDAnalysisData/
  dev_url: https://github.com/MDAnalysis/MDAnalysisData

extra:
  recipe-maintainers:
    - kain88-de
    - orbeckst
    - richardjgowers
