{% set name = "MDAnalysisData" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 11cbd4a7ebd1df5176fa3e5d18894a5049594471bd80297cc157aaace3c9970c

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - setuptools
    - tqdm

test:
  requires:
    - python {{ python_min }}
  imports:
    - MDAnalysisData

about:
  home: https://github.com/MDAnalysis/MDAnalysisData
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Example MD Simulation Data
  description: |
    The MDAnalysisData package unifies access to test and example
    trajectories that can be used for workshops and extended tests.
  doc_url: https://www.mdanalysis.org/MDAnalysisData/
  dev_url: https://github.com/MDAnalysis/MDAnalysisData

extra:
  recipe-maintainers:
    - kain88-de
    - orbeckst
    - richardjgowers
