travis:
  secure:
    BINSTAR_TOKEN: x0ijT5EmdO2EVdrUGA/wtCxNIRcC8yHcmJ+jYzoH9RLSXGllcnSDhGOjBBtiF9LTVr0gWaUmL1XQyJwSFC0AU1thFWYFUqpeqYe6eOamY7HO16Y29AGKsp8iV4FUw4lSjxWIAxfdBfIvorx7kvpUQDueZudL3ZT4PlHdtiRzhvpna6b44OQWvD7kmemtiVaw/LZ4WCXlwVJk37jhM1vrqO1n6OcafwGbsnsJilcaKuBrJ2AGKtfCxegB6rBN/A616wTe++SXNFxgY5jqGQn6J2XtR9fl6ZCxEizNkWw75tcxKqwAOgVdwTvERb6lejumo9BXFUbNlNQ6xKOKje2MLpokg7bntq82iXaWZ9FQ8ECtxdkxFjh3ZhzL+eSQTayer5We/Gbpj5ot2ewfZrlufm9UmXZlGXjXR9bhkCDlA+/QJ0WQOt9hBiPPXdrln2IDWfG7cXs0ZUhZChhpViVDVEycduw2ZXO9qfLGP40Hfeab3ptlMWb0JR6VuN56ln4iwvp8qWEGpYDh8ZMvTYUSk2FSXqq/yXO2vNfT9qkMQPFHg5zNKEDvfqYOpLTM+aZKQQswKbZz3jfL9en93pqoh0LgDdDp1Y41M9Ddsa+O6Df6AkLrmdvxmigozpdPN4zGZAav+ABbOxBfGFoi7BqYlXJ9l7K3qbX0alUsif3a9Vs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
